/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library auth.src.open_id_type;

class OpenIDType {
  static const int sina = 0;
  static const int qq = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    sina
    , qq
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    sina: 'sina'
    , qq: 'qq'
  };
}
