/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library auth.src.user_type;

class UserType {
  static const int MEMBER = 1;
  static const int CAREGIVER = 2;

  static final Set<int> VALID_VALUES = new Set.from([
    MEMBER
    , CAREGIVER
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    MEMBER: 'MEMBER'
    , CAREGIVER: 'CAREGIVER'
  };
}
