/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library auth;

export 'src/open_id_type.dart' show OpenIDType;
export 'src/user_type.dart' show UserType;
export 'src/login_ext_info.dart' show LoginExtInfo;
export 'src/open_account_info.dart' show OpenAccountInfo;
export 'src/logout_ext_info.dart' show LogoutExtInfo;
export 'src/auth_user_info.dart' show AuthUserInfo;
export 'src/login_result_ext_info.dart' show LoginResultExtInfo;
export 'src/login_result.dart' show LoginResult;
export 'src/auth_service.dart' show AuthService;
export 'src/auth_service.dart' show AuthServiceClient;
export 'src/auth_service.dart' show AuthServiceProcessor;
