/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library shared;

export 'src/shared_struct.dart' show SharedStruct;
export 'src/shared_service.dart' show SharedService;
export 'src/shared_service.dart' show SharedServiceClient;
export 'src/shared_service.dart' show SharedServiceProcessor;
