/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

library account;

export 'src/gender.dart' show Gender;
export 'src/account_info.dart' show AccountInfo;
export 'src/account_service.dart' show AccountService;
export 'src/account_service.dart' show AccountServiceClient;
export 'src/account_service.dart' show AccountServiceProcessor;
