/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library xkcm.src.device_type;

class DeviceType {
  static const int WEB = 1;
  static const int XK_WATCH = 101;
  static const int XK_TERMINAL = 201;
  static const int ANDROID = 1001;
  static const int IOS = 1002;

  static final Set<int> VALID_VALUES = new Set.from([
    WEB
    , XK_WATCH
    , XK_TERMINAL
    , ANDROID
    , IOS
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    WEB: 'WEB'
    , XK_WATCH: 'XK_WATCH'
    , XK_TERMINAL: 'XK_TERMINAL'
    , ANDROID: 'ANDROID'
    , IOS: 'IOS'
  };
}
