/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library xkcm.src.language;

class Language {
  static const int ZH_CN = 0;
  static const int EN_US = 1;

  static final Set<int> VALID_VALUES = new Set.from([
    ZH_CN
    , EN_US
  ]);
  static final Map<int, String> VALUES_TO_NAMES = {
    ZH_CN: 'ZH_CN'
    , EN_US: 'EN_US'
  };
}
