/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
library xkcm.src.return_message;

import 'dart:typed_data' show Uint8List;
import 'package:thrift/thrift.dart';
import 'package:xkcm/xkcm.dart';

class ReturnMessage implements TBase {
  static final TStruct _STRUCT_DESC = new TStruct("ReturnMessage");
  static final TField _IS_SUCCEED_FIELD_DESC = new TField("isSucceed", TType.BOOL, 1);
  static final TField _MESSAGE_FIELD_DESC = new TField("message", TType.STRING, 2);

  bool _isSucceed = false;
  static const int ISSUCCEED = 1;
  String _message;
  static const int MESSAGE = 2;

  bool __isset_isSucceed = false;

  ReturnMessage() {
  }

  // isSucceed
  bool get isSucceed => this._isSucceed;

  set isSucceed(bool isSucceed) {
    this._isSucceed = isSucceed;
    this.__isset_isSucceed = true;
  }

  bool isSetIsSucceed() => this.__isset_isSucceed;

  unsetIsSucceed() {
    this.__isset_isSucceed = false;
  }

  // message
  String get message => this._message;

  set message(String message) {
    this._message = message;
  }

  bool isSetMessage() => this.message != null;

  unsetMessage() {
    this.message = null;
  }

  getFieldValue(int fieldID) {
    switch (fieldID) {
      case ISSUCCEED:
        return this.isSucceed;
      case MESSAGE:
        return this.message;
      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
      case ISSUCCEED:
        if (value == null) {
          unsetIsSucceed();
        } else {
          this.isSucceed = value;
        }
        break;

      case MESSAGE:
        if (value == null) {
          unsetMessage();
        } else {
          this.message = value;
        }
        break;

      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  // Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise
  bool isSet(int fieldID) {
    switch (fieldID) {
      case ISSUCCEED:
        return isSetIsSucceed();
      case MESSAGE:
        return isSetMessage();
      default:
        throw new ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  read(TProtocol iprot) {
    TField field;
    iprot.readStructBegin();
    while (true) {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case ISSUCCEED:
          if (field.type == TType.BOOL) {
            this.isSucceed = iprot.readBool();
            this.__isset_isSucceed = true;
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case MESSAGE:
          if (field.type == TType.STRING) {
            this.message = iprot.readString();
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  write(TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    oprot.writeFieldBegin(_IS_SUCCEED_FIELD_DESC);
    oprot.writeBool(this.isSucceed);
    oprot.writeFieldEnd();
    if (this.message != null) {
      oprot.writeFieldBegin(_MESSAGE_FIELD_DESC);
      oprot.writeString(this.message);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  String toString() {
    StringBuffer ret = new StringBuffer("ReturnMessage(");

    ret.write("isSucceed:");
    ret.write(this.isSucceed);

    ret.write(", ");
    ret.write("message:");
    if (this.message == null) {
      ret.write("null");
    } else {
      ret.write(this.message);
    }

    ret.write(")");

    return ret.toString();
  }

  validate() {
    // check for required fields
    // check that fields of type enum have valid values
  }

}

